## HaloFeedback

**Units:**
    - Masses [M_sun]
    - Times [s]
    - Distances [pc]
    - Speeds [km/s]

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import HaloFeedback

#### Initialisation

Initialise a distribution function:

In [5]:
DF1 = HaloFeedback.DistributionFunction()

#This defaults to some standard values for the 
#density profile and masses:

print(DF1.gamma)
print(DF1.M_BH, " M_sun")
print(DF1.M_NS, " M_sun")
print(DF1.rho_sp, " M_sun/pc^3")

2.3333333333333335
1000.0  M_sun
1.0  M_sun
226  M_sun/pc^3


Otherwise, you can specify the values you're interested in:

In [6]:
DF2 = HaloFeedback.DistributionFunction(gamma = 2.5, M_BH = 1e4, M_NS = 1, rho_sp = 226.)

#### Extracting the density

The density at a given radius is extracted with:

In [8]:
DF2.rho(1e-8)

3.2998630442367827e+22

This calculates the density numerically from the internally stored distribution function $f(\mathcal{E})$.

If we want to calculate the density of particles at a given radius with speeds below some v_cut, then we can do:

In [14]:
DF2.rho(1e-8, v_cut = 1e4)

1.0263925607183992e+20

#### Evolving the system

The internal distribution function $f(\mathcal{E})$ is stored as a grid over $\mathcal{E}$ values:

In [16]:
DF2.eps_grid

array([1.49792530e+10, 1.49564779e+10, 1.49337375e+10, ...,
       3.70902548e+03, 3.70338613e+03, 3.69775535e+03])

In [17]:
DF2.f_eps

array([8.59131345e+07, 8.57825087e+07, 8.56520815e+07, ...,
       2.12730238e+01, 2.12406794e+01, 2.12083843e+01])

For a compact object at radius $r_0$ with velocity $v_0$, the time derivative of the distribution function can be calculated using:

In [20]:
r0 = 1e-8 #pc
v0 = 5e4 #km/s
DF2.dfdt(r0, v0)

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
       6.57611942e-16, 6.55115144e-16, 6.52627826e-16])

Again, if we want to scatter only with particles with speed smaller than some v_cut, we can use:

In [25]:
DF2.dfdt(r0, v0, v_cut = 2e4)

array([0., 0., 0., ..., 0., 0., 0.])

Note that typically v_cut will be equal to the orbital speed of the compact object.

Finally, then, we update the internal distribution function using:

In [29]:
dt = 1 #second
DF2.f_eps += DF2.dfdt(r0, v0, v_cut = 2e4)*dt
#In the 'EvolutionPlot.py' file, I evolve using the improved Euler method, which should be more stable...

Then we can recompute the density:

In [30]:
DF2.rho(r0)

3.2998630621311138e+22